### ISSUE TITLE
Implement Events ViewPager

### ISSUE THREAD

**Issue by SeanTaylorLane** [HackRU/one-app-android#12]
Some guidelines for implementing events:
* Watch [this video](https://www.youtube.com/watch?v=zQekzaAgIlQ), it's a quick guide to using ViewPager. It's an old video, so make sure you check the current [reference](https://developer.android.com/reference/android/support/v4/view/ViewPager)
   - Use a `FragmentStatePagerAdapter`
* Each page in the ViewPager will be a fragment that contains a RecyclerView. I've already created these fragments. These fragments are called `SaturdayFragment` and `SundayFragment` and both use the same layout file `fragment_saturday_sunday.xml`.
* You don't need to change anything about `SaturdayFragment` or `SundayFragment`
* All you need to do is set up the ViewPager inside `EventsFragment` so that you can swipe between `SaturdayFragment` and `SundayFragment`

Thanks and good luck! If you have difficulty, don't be afraid to contact me on Discord or leave a comment on this thread

**Comment by dhruvilp** [comment]
It's already done a long time ago :)
