### ISSUE TITLE
README and put things on master

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/one-app-android#8]
Please have an R&D README. Here's a template: https://github.com/HackRU/handbook/blob/master/projects/projects-template.md

Please follow it as closely as you can.

Also, please merge changes into master, so that we know what the currently "prepared" version of the app is. This'll help us figure out what works and what doesn't and help architects get on-boarded.

We can talk here if you need to git help.

**Comment by SeanTaylorLane** [comment]
LOL git help good one
